import Header from "@/sections/header/Header";
import "./globals.css";
import Footer from "@/sections/Footer/Footer";
import { Toaster } from "sonner";
import { PublicEnvScript } from "next-runtime-env";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <PublicEnvScript />
      </head>
      <body>
          {children}
          <Toaster position="top-center" richColors/>
      </body>
    </html>
  );
}
