import Header from "@/sections/header/Header";
import "./globals.css";
import Footer from "@/sections/Footer/Footer";
import { Toaster } from "sonner";
import { PublicEnvScript } from "next-runtime-env";
import UserProvider from "@/context/user_context";
import LanguageProvider, { useLanguage } from "@/context/language_context";
import LanguageSwitcher from "@/data/locales/LanguageSwitcher";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html >
      <head>
        <PublicEnvScript />
      </head>

      <body>
        
          <UserProvider>
          <LanguageProvider>
            <LanguageSwitcher/>
            {children}
            </LanguageProvider>
          </UserProvider>
          <Toaster position="top-center" richColors />
        
      </body>
    </html>
  );
}
